name: javad
services:
  app:
    container_name: app
    build: ./docker
    #user: "1000:1000"
    ports:
      - "8008:80"
    volumes:
      # Mount source-code for development
      - ./:/var/www/html
    networks:
      - javad-net
    depends_on:
      - db
      - phpmyadmin
  db:
    image: mysql:8.2
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - javad-net
  phpmyadmin:
    container_name: admin
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - "7272:80"
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 3000M
    networks:
      - javad-net
  redis:
    image: redis:8.2.2
    container_name: redis
    command: >
      redis-server
        --requirepass "${REDIS_PASSWORD}"
        --appendonly yes
        --appendfilename "appendonly.aof"
        --save "60 1"
        --maxmemory 256mb
        --maxmemory-policy allkeys-lru
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis:/data
    networks:
      - javad-net

networks:
  javad-net:
    external: false

