; ------------------------------
; Core
; ------------------------------
memory_limit = 512M
max_execution_time = 60
max_input_time = 60
post_max_size = 100M
upload_max_filesize = 100M
date.timezone = Asia/Tehran

; ------------------------------
; Error handling
; ------------------------------
display_errors = Off
display_startup_errors = Off
log_errors = On
error_reporting = E_ALL

; ------------------------------
; Opcache (Recommended for Laravel)
; ------------------------------
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2

; ------------------------------
; Redis
; ------------------------------
redis.session.locking_enabled = 1
redis.session.lock_retries = 10
redis.session.lock_wait_time = 2000

; ------------------------------
; Security
; ------------------------------
expose_php = Off
